"""add onboarding_completed field to users table

Revision ID: 5bd8e6bac68a
Revises: f5e324c9b416
Create Date: 2025-09-25 00:15:27.151387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5bd8e6bac68a"
down_revision: Union[str, Sequence[str], None] = "f5e324c9b416"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("onboarding_completed", sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "onboarding_completed")
    # ### end Alembic commands ###
