"""add avatar_url column if not exists

Revision ID: b3beb2c8c5f9
Revises: 5f0efc346e29
Create Date: 2025-10-07 21:36:01.455334

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3beb2c8c5f9"
down_revision: Union[str, Sequence[str], None] = "5f0efc346e29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
