"""sync_database_with_current_models

Revision ID: de25937a4cf7
Revises: 5316b26f30f9
Create Date: 2025-10-09 18:44:25.239076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de25937a4cf7'
down_revision: Union[str, Sequence[str], None] = '5316b26f30f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_messages', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_room_messages_room_id_created_at'), table_name='room_messages')
    op.drop_index(op.f('ix_room_messages_created_at'), table_name='room_messages')
    op.create_index('idx_room_message_room_id', 'room_messages', ['room_id'], unique=False)
    op.create_index('idx_room_message_user_id', 'room_messages', ['user_id'], unique=False)
    op.drop_constraint(op.f('room_messages_user_id_fkey'), 'room_messages', type_='foreignkey')
    op.create_foreign_key(None, 'room_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('room_participants', 'is_muted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('room_participants', 'is_speaking',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('idx_room_participants_room_id'), table_name='room_participants')
    op.drop_index(op.f('idx_room_participants_user_id'), table_name='room_participants')
    op.drop_constraint(op.f('uq_room_participant_user'), 'room_participants', type_='unique')
    op.create_index('idx_room_participant_room_id', 'room_participants', ['room_id'], unique=False)
    op.create_index('idx_room_participant_user_id', 'room_participants', ['user_id'], unique=False)
    op.create_index('idx_task_completed', 'tasks', ['completed'], unique=False)
    op.create_index('idx_task_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_task_priority', 'tasks', ['priority'], unique=False)
    op.alter_column('user_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('user_settings_user_id_key'), 'user_settings', type_='unique')
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.drop_constraint(op.f('user_settings_user_id_fkey'), 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key(op.f('user_settings_user_id_fkey'), 'user_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.create_unique_constraint(op.f('user_settings_user_id_key'), 'user_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_settings', 'updated_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_settings', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('idx_task_priority', table_name='tasks')
    op.drop_index('idx_task_due_date', table_name='tasks')
    op.drop_index('idx_task_completed', table_name='tasks')
    op.drop_index('idx_room_participant_user_id', table_name='room_participants')
    op.drop_index('idx_room_participant_room_id', table_name='room_participants')
    op.create_unique_constraint(op.f('uq_room_participant_user'), 'room_participants', ['room_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_room_participants_user_id'), 'room_participants', ['user_id'], unique=False)
    op.create_index(op.f('idx_room_participants_room_id'), 'room_participants', ['room_id'], unique=False)
    op.alter_column('room_participants', 'is_speaking',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('room_participants', 'is_muted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'room_messages', type_='foreignkey')
    op.create_foreign_key(op.f('room_messages_user_id_fkey'), 'room_messages', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_room_message_user_id', table_name='room_messages')
    op.drop_index('idx_room_message_room_id', table_name='room_messages')
    op.create_index(op.f('ix_room_messages_created_at'), 'room_messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_room_messages_room_id_created_at'), 'room_messages', ['room_id', 'created_at'], unique=False)
    op.alter_column('room_messages', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###