name: Deploy Frontend

on:
  push:
    branches: ["main"]
    paths:
      - 'frontend/**'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        working-directory: frontend/clockko-wellness-app
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: frontend/clockko-wellness-app
        run: pnpm build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::474422890464:role/clockko-gha-role
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Provision/Update frontend infra
        run: |
          cd frontend/infra
          terraform init -input=false
          terraform apply -auto-approve -input=false

      - name: Sync build to S3
        run: |
          BUCKET=$(cd frontend/infra && terraform output -raw website_bucket)
          aws s3 sync frontend/clockko-wellness-app/dist s3://$BUCKET/ --delete --cache-control "public, max-age=60"

      - name: Output site URL
        run: |
          cd frontend/infra
          terraform output website_url
