name: Deploy Frontend to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "frontend/clockko-wellness-app/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup pnpm first
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Setup Node.js and enable pnpm cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: frontend/clockko-wellness-app/pnpm-lock.yaml

      # Speed Boost — Cache pnpm store for faster installs
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('frontend/clockko-wellness-app/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Verify pnpm version
      - name: Check pnpm version
        run: pnpm --version

      # Build the React + TypeScript app
      - name: Build frontend
        working-directory: frontend/clockko-wellness-app
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          VITE_BASE: "/clockko-team04-althub-project/"
          VITE_GOOGLE_CLIENT_ID: ${{ vars.VITE_GOOGLE_CLIENT_ID }}
        run: |
          pnpm install
          pnpm build

      # Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/clockko-wellness-app/dist

  # Deploy to GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
